### ISSUE TITLE
Post Process failed Folder path value is lost on restart of Mylar

### ISSUE THREAD

**Issue by quark5980** [ferretcomp/mylar#8]
Post Process failed Folder path value is lost on restart of Mylar

The checkbox stays checked but the path value is lost

**Comment by ferretcomp** [comment]
This is fixed in the current release. 

Though it still tried to move the file to none, which broke stuff. will add a check to make sure the that the value isn't 'none' and that target dir exists.

**Comment by ferretcomp** [comment]
fixed in [master d80c4d8]
